### ISSUE TITLE
建议增加预热功能

### ISSUE THREAD

**Issue by yourtion** [leizongmin/leizm-benchmark#1]
如果函数执行前没有进行预热（包括连接池连接的预热，或者函数JIT的预热，会对结果产生影响）

见下图：

![image](https://user-images.githubusercontent.com/1475301/50593841-1c789c00-0ed5-11e9-87e3-d3a2c198385b.png)

`preheat` 跟 `get without rest` 执行的代码是一致的。但是结果差距有点大，可能是一开始 Redis 连接没有建立等原因导致

**Comment by leizongmin** [comment]
`@leizm/benchmark@2.0.0` 版本已经支持 `preheat` 参数设置预热时间。
